logging:
  file: 
    name: ansibleService
    path: /apps/OpsERA/logs/components/ansible-service
spring:
  application:
    name: ansible-service
    description: API interacting with ansible endpoints
  lifecycle:
    timeout-per-shutdown-phase: 2h
  servlet:
     multipart:
       max-file-size: 100MB
       max-request-size: 100MB
  task:
    execution:
      pool:
        core-size: 50
        queue-capacity: 100 
        max-size: 200
      shutdown:
        await-termination: true
        await-termination-period: 2h
      thread-name-prefix: AnsibleAsyncThread-
server:
  port: 9080
  shutdown: graceful

pipeline:
  config:
    baseurl: ${opsera.config.baseurl}/api/pipeline
customer:
  config:
    baseurl: ${opsera.config.baseurl}/api/customer/
---

spring:
  profiles: kubernetes
kafka:
  consumer:
    bootstrapServer: ${OPSERA_KAFKA_BOOTSTRAP_URL:kafka.kafka.svc.cluster.local:9092}
    groupId: ansible-service
opsera:
  config:
    baseurl: ${OPSERA_API_SERVICE_URL:http://opsera-apigateway.microservices.svc.cluster.local:9091}

---

spring:
  profiles: local
pipeline:
  config:
    baseurl: https://apigateway.opsera-dev-private.opsera.io/api/pipeline
customer:
  config:
    baseurl: https://apigateway.opsera-dev-private.opsera.io/api/customer/
kafka:
  consumer:
    bootstrapServer: abfddd837c0914516aeff9f3ef667b10-866acafb6124ce47.elb.us-east-2.amazonaws.com:9094
    groupId: s3-log-pusher
amazonProperties:
  accessKey: AKIAWNKXHD3I53KF2WOT
  secretKey: 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
