logging:
  file: 
    name: ansibleService
    path: /apps/OpsERA/logs/components/ansible-service
hosted:
  zoneId: Z1TIQL15FE1S33
spring:
  application:
    name: ansible-service
    description: API interacting with ansible endpoints
  lifecycle:    timeout-per-shutdown-phase: 2h
  servlet:
     multipart:
       max-file-size: 100MB
       max-request-size: 100MB
  task:
    execution:
      pool:
        core-size: 50
        queue-capacity: 100 
        max-size: 200
      shutdown:
        await-termination: true
        await-termination-period: 2h
      thread-name-prefix: AnsibleAsyncThread-
server:
  port: 9080
  shutdown: graceful
---

spring:
  profiles: kubernetes
pipeline:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/pipeline
vault:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/vault
customer:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/customer/
kafka:
  config:
    baseurl: http://opsera-apigateway.microservices.svc.cluster.local:9091/api/kafka
  consumer:
    bootstrapServer: kafka.kafka.svc.cluster.local:9092
    groupId: s3-log-pusher
amazonProperties:
  accessKey: AKIAWNKXHD3IUKQXB3FI
  secretKey: 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

---

spring:
  profiles: local
pipeline:
  config:
    baseurl: https://apigateway.opsera-dev-private.opsera.io/api/pipeline
vault:
  config:
    baseurl: https://apigateway.opsera-dev-private.opsera.io/api/vault
customer:
  config:
    baseurl: https://apigateway.opsera-dev-private.opsera.io/api/customer/
kafka:
  config:
    baseurl: https://apigateway.opsera-dev-private.opsera.io/api/kafka
  consumer:
    bootstrapServer: abfddd837c0914516aeff9f3ef667b10-866acafb6124ce47.elb.us-east-2.amazonaws.com:9094
    groupId: s3-log-pusher
amazonProperties:
  accessKey: AKIAWNKXHD3IUKQXB3FI
  secretKey: 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